django_cms_example/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^admin-cms/', include('cms.urls')),
    url(r'^', include('user_app.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

user_app/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from . import views, auth_views, api_views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.index),
    # url(r'^signup/$', views.signup, name='user-register'),
    # url(r'^logout/$', views._logout, name='logout'),
    # url(r'^login/$', views._login, name='login'),
    url(r'cabinet/$', views.cabinet, name='cabinet'),
    url(r'show-template/(?P<id>[0-9]+)/$', views.show_template, name='show-template'),
    url(r'set-template/(?P<id_template>[0-9]+)/$', views.set_template, name='set-template'),
    url(r'contact-form/$', views.contact_form, name='contact-form'),
    url(r'start/$', views.start, name='start'),
    url(r'about-us/$', views.about, name='about'),
    url(r'advertisement/$', views.advertisement, name='advertisement'),
    url(r'templates/$', views.templates, name='templates'),
    url(r'user-profile/$', views.user_profile, name='user_profile'),
    url(r'contactus/$', views.contactus, name='contactus'),
    url(r'my-profile/$', views.my_profile, name='my-profile'),
    url(r'contact-form-page/$', views.contact_form_page, name='contact_form_page'),
    url(r'create-new/$', views.create_new, name='create-new'),
    url(r'^statistic/$', views.statistics, name='statistics'),
    url(r'^profile-form/$', views.profile_form, name='profile-form'),

]

auth_urls = [
    url(r'user-login/$', auth_views.user_login, name='user-login'),
    url(r'user-register/$', auth_views.user_register, name='user-register'),
    url(r'user-logout/$', auth_views.user_logout, name='user-logout'),
]

api_urls = [
    url(r'^statistic/(?P<page_id>[0-9]+)/$', api_views.EArticleView.as_view()),

    url(r'^set_status/(?P<query_id>[0-9]+)/$', api_views.set_status),
]

urlpatterns += auth_urls
urlpatterns += api_urls

user_app/models.py
from cms.models.pluginmodel import CMSPlugin
from cms.models.pagemodel import Page

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from djangocms_text_ckeditor.fields import HTMLField

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default='')
    avatar = models.ImageField(upload_to='avatar', blank=True,
                               null=True, default='')
    description = models.CharField(max_length=5000, verbose_name='About me', blank=True,
                                   null=True, default='')
    full_name = models.CharField(max_length=300, verbose_name='Full name', blank=True,
                                 null=True, default='')
    about_me = models.TextField(max_length=600, verbose_name='About me', blank=True,
                                null=True, default='')


class Hello(CMSPlugin):
    guest_name = models.CharField(max_length=50, default='Guest')


class CallBackForm(CMSPlugin):
    email = models.CharField(max_length=255, verbose_name='E-mail', blank=True, null=True, default='')
    phone = models.CharField(max_length=255, verbose_name='Phone', blank=True, null=True, default='')


class ReviewItem(CMSPlugin):
    image = models.ImageField(upload_to='review_image',
                              verbose_name='Photo review',
                              blank=True, null=True)
    text = models.TextField(max_length=1555, verbose_name='Message review', blank=True, null=True)
    author_review = models.CharField(max_length=255, verbose_name='author review', blank=True, null=True)
    country_author = models.CharField(max_length=255, verbose_name='country', blank=True, null=True)
    txt = models.CharField(max_length=10)


class PageByUser(models.Model):
    page_user_custom = models.ForeignKey(Page, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.TextField(max_length=1000, verbose_name='Category')
    image = models.ImageField(upload_to='image_template', blank=True, null=True)

    def __str__(self):
        return self.category + ' ' + self.user.username + ' ' + self.page_user_custom.get_title()

    def views(self, **kwargs):
        return Statistic.objects.filter(page=self)

    def count_sum(self):
        count_sum = 0
        for page in self.views():
            count_sum += page.count
        return count_sum

    def check_published(self):
        current_page = Page.objects.get(pagebyuser=self)
        return current_page.is_published('ru')


class PageByUserStatistic(models.Model):
    page_stat = models.ForeignKey(PageByUser)  # внешний ключ на статью
    date = models.DateField('Дата', default=timezone.now)  # дата
    views = models.IntegerField('Просмотры', default=0)  # количество просмотров в эту дату

    def __str__(self):
        return str(self.date)


class Statistic(models.Model):
    MONTH = (
        ('Jan', 'January'),
        ('Feb', 'February'),
        ('Mar', 'March'),
        ('Apr', 'April'),
        ('May', 'May'),
        ('Jun', 'June'),
        ('Jul', 'July'),
        ('Aug', 'August'),
        ('Sep', 'September'),
        ('Oct', 'October'),
        ('Nov', 'November'),
        ('Dec', 'December')
    )
    page = models.ForeignKey(PageByUser, on_delete=models.CASCADE)
    month = models.CharField(max_length=55, choices=MONTH)
    count = models.IntegerField()

    def __str__(self):
        return 'month - {} page-{}; count -{}'.format(self.month, self.page, self.count)


class CallBack(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    theme = models.CharField(max_length=255, verbose_name='Theme message')
    email = models.CharField(max_length=255, verbose_name='Email')
    phone = models.CharField(max_length=255, verbose_name='Phone')
    name_human = models.CharField(max_length=255, verbose_name='Name user')
    message = models.TextField(max_length=10000, verbose_name='Message')
    status = models.BooleanField(verbose_name='Viewed', default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'page is {} theme is {}'.format(self.page, self.theme)


class ArticlePluginModel(CMSPlugin):
    title = models.CharField(max_length=50)

    def copy_relations(self, oldinstance):
        print('copy_relations')
        for associated_item in oldinstance.associated_item.all():
            # instance.pk = None; instance.pk.save() is the slightly odd but
            # standard Django way of copying a saved model instance
            associated_item.pk = None
            associated_item.plugin = self
            associated_item.save()

    def render(self, context, instance, placeholder):
        print('render!!!!!!!!!!!')
        # context.update({
        #     'product': instance.product,
        #     'object': instance,
        #     'placeholder': placeholder
        # })

        return context


class SlidePluginModel(CMSPlugin):
    image = models.ImageField(upload_to='slides_images')

    def copy_relations(self, oldinstance):
        print('copy_relations')
        for associated_item in oldinstance.SliderImage_item.all():
            # instance.pk = None; instance.pk.save() is the slightly odd but
            # standard Django way of copying a saved model instance
            associated_item.pk = None
            associated_item.plugin = self
            associated_item.save()

    def render(self, context, instance, placeholder):
        # print('render!!!!!!!!!!!')
        return context


class SliderImage(models.Model):
    plugin = models.ForeignKey(
        SlidePluginModel,
        related_name="SliderImage_item"
    )


class PopupPluginModel(CMSPlugin):
    image = models.ImageField(upload_to='popup_slides')
    title  = models.CharField(max_length=255 , verbose_name='Short description' , blank=True , null=True , default='')
    text = HTMLField(configuration='CKEDITOR_SETTINGS_MODEL1', default='')


    def copy_relations(self, oldinstance):
        print('copy_relations')
        for associated_item in oldinstance.popup_item.all():
            # instance.pk = None; instance.pk.save() is the slightly odd but
            # standard Django way of copying a saved model instance
            associated_item.pk = None
            associated_item.plugin = self
            associated_item.save()

class Popup(models.Model):
    plugin  = models.ForeignKey(PopupPluginModel , related_name="popup_item" )

class AssociatedItem(models.Model):
    plugin = models.ForeignKey(
        ArticlePluginModel,
        related_name="associated_item"
    )


class HeaderCoverImgText(CMSPlugin):
    image = models.ImageField(upload_to='header_user_img',
                              verbose_name='header_user_img',
                              blank=True, null=True)
    title = models.CharField(max_length=255, verbose_name='Title', blank=True, null=True)
    text = models.TextField(max_length=500, verbose_name='Short description', blank=True, null=True)


class TitleText(CMSPlugin):
    title = models.CharField(max_length=1000, verbose_name='Title block')
    text = models.TextField(max_length=5000, verbose_name='description', blank=True, null=True)


class Video(CMSPlugin):
    file = models.FileField(upload_to='pres_video', blank=True, null=True)
    autoplay = models.BooleanField(default=True, verbose_name='autoplay')
    controls = models.BooleanField(default=False, verbose_name='Show controls')


#



class BusCardAvatar(CMSPlugin):
    avatar = models.ImageField(upload_to='user_avatar', default='', blank=True, null=True, )
    background = models.ImageField(upload_to='back_buss_card', default='', blank=True, null=True, )
    title = models.CharField(max_length=200, verbose_name='Title', default='')
    text = HTMLField(configuration='CKEDITOR_SETTINGS_MODEL1', default='')
    phone_1 = models.CharField(max_length=20, verbose_name='First phone number',
                               blank=True, null=True, default='')
    phone_2 = models.CharField(max_length=20, verbose_name='Second phone number',
                               blank=True, null=True, default='')
    phone_3 = models.CharField(max_length=20, verbose_name='Third phone number',
                               blank=True, null=True, default='')
    email = models.CharField(max_length=50, verbose_name='Email',
                             blank=True, null=True, default='')
    address = models.CharField(max_length=255, verbose_name='Address',
                               blank=True, null=True, default='')


class BusCardAvatarOneImage(CMSPlugin):
    avatar = models.ImageField(upload_to='user_avatar', default='')
    background = models.ImageField(upload_to='back_buss_card', default='')
    right_top_image = models.ImageField(upload_to='back_buss_card', default='')
    title = models.CharField(max_length=200, verbose_name='Title', default='')
    description = HTMLField(configuration='CKEDITOR_SETTINGS_MODEL1', default='')
    text = HTMLField(configuration='CKEDITOR_SETTINGS_MODEL1', default='')
    phone_1 = models.CharField(max_length=20, verbose_name='First phone number',
                               blank=True, null=True, default='')
    phone_2 = models.CharField(max_length=20, verbose_name='Second phone number',
                               blank=True, null=True, default='')
    phone_3 = models.CharField(max_length=20, verbose_name='Third phone number',
                               blank=True, null=True, default='')
    email = models.CharField(max_length=50, verbose_name='Email',
                             blank=True, null=True, default='')
    address = models.CharField(max_length=255, verbose_name='Address',
                               blank=True, null=True, default='')


class BusCardAvatarTwoImage(CMSPlugin):

user_app/forms.py
from cms.models.pagemodel import Page, PageType
import django.forms as forms


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        # fields = '__all__'
        exclude = ['slug']

    def save(self, commit=True):
        print('save!!!!!!')


from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

my_default_errors = {
    'required': 'This field is required',
    'invalid': 'Enter a valid value'
}

# < a
# href = "{% url 'user-login' %}"

#
# class ="personal_info js-auth-show header-icon user-icon" > Log in < img src="{% static 'in.svg' %}"
#
#
# alt = "" > < / a >

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = "Ваш e-mail"
        self.fields['username'].label = "Логін"
        self.fields['password1'].label = "Пароль"
        self.fields['password2'].label = "Пітвердіть пароль"
        self.fields['password2'].widget.attrs['class'] = 'password'
        self.fields['password1'].widget.attrs['class'] = 'password'

        # self.fields['username'](error_messages=my_default_errors)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'] = 'Логін'
        self.fields['password'] = 'password1'

django_cms_example/templates/user_app/add_form.html
<h1 class="title-form add_form">Create new card</h1>

<div class="form_main add_form">
    <div class="container">
        <form action="{% url 'set-template' id_template=id_template %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div>
                <input type="hidden" name="source" id="id_source">
            </div>
        <div class="form-group" >
                <input type="file" name="image" id="id_image" style="outline: none;">
                <label class="control-label" for="id_image" >Load the main image of your card</label>

            </div>
        <div class="field-form form-group">
                <input type="text" name="title" id="id_title" maxlength="255" required>
                <label class="control-label" for="id_title" >Title</label><i class="bar"></i>

            </div>
            <div class="field-form form-group" style="margin-top: 20px;">
                <input type="text" name="description" id="id_description" maxlength="500" required>
                <label class="control-label" for="id_description" >Description</label><i class="bar"></i>

            </div>


<div class="form-group">
            <select name="parent_page" id="">
                {% for elem in level_2 %}
                    <option value="{{ elem}}">{{ elem}}</option>
                {% endfor %}
            </select>
<label for="select" class="control-label">Category</label><i class="bar"></i>
            {% for elem in type_pages %}

                {% if elem.get_title == current_page.get_parent_page.get_title %}
                    <!--<input type="hidden" name="parent_page" value="{{current_page.get_parent_page.get_title}}">-->

    <input type="hidden" name="type_page" value={{ id_template}}>
                {% endif %}
            {% endfor %}
</div>
        <div class="btn-popup-wrap button-container">
                <button class="button"><span>Create</span></button>
            </div>
        </form>
    </div>
</div>

django_cms_example/templates/user_app/cabinet.html
{% extends 'user_app/index.html' %}
{% load static %}

{% block body %}
<div class="advertisement">

    <div class="advert_block">
        <div class="left_col cab">
            <ul class="category_list">
                <li class="{% if current_page == 'profile' %}active{% endif %}">
                    <a href="{% url 'my-profile' %}">Profile</a>
                </li>
                <li class="{% if current_page == 'my_template' %}active{% endif %}">
                    <a href="/cabinet/">My templates</a>
                </li>
                <li class="{% if current_page == 'create_new' %}active{% endif %}">
                    <a href="{% url 'create-new' %}">Create new template</a>
                </li>
                <li class="{% if current_page == 'statistic' %}active{% endif %}">
                    <a href="{% url 'statistics' %}">Statistics</a>
                </li>
                <li class="{% if current_page == 'contact_form_page' %}active{% endif %}">
                    <a href="{% url 'contact_form_page' %}">Contact form</a>
                </li>
            </ul>
        </div>
        <div class="right_col cab ">
            {% block cabinet %}
            <div class="advertisement">
                <div class="main_menu templ_my">
                    <div class="right_col temp_col templ_my">
                        <div class="choose_type">
                            <form method="post" action="/">
                                <div class="form-radio">

                                    <div class="radio">
                                        <label>
                                            <input class="js-check-status" id="publish"
                                                   type="radio"
                                                   name="status"
                                                   value="True"/><i class="helper"></i>Publish
                                        </label>


                                        <label>
                                            <input class="js-check-status" id="unpublish"
                                                   type="radio"
                                                   name="status"
                                                   value="False"/><i class="helper"></i>UnPublish
                                        </label>


                                        <label>
                                            <input class="js-check-status" id="all"
                                                   type="radio"
                                                   name="status"
                                                   value="all" checked="checked"/><i class="helper"></i>All
                                        </label>

                                    </div>


                                </div>
                            </form>
                        </div>
                        <!--<div class="d6">-->
                            <!--<form>-->
                                <!--<input type="text" placeholder="Search...">-->
                                <!--<button type="submit"><img src="{% static 'magnifier.svg' %}" alt=""></button>-->
                            <!--</form>-->
                        <!--</div>-->
                    </div>
                </div>
                <div class="advert_block">
                    <div class="right_col create_templs ">
                        <div class="content_user_templ templ_my">
                            {% for page in user_pages %}
                            {% if page.image %}
                            {% endif %}

                            <div class="js-template-cabinet user_templ"
                                 data-publish="{{ page.check_published }}">
                                <div class="img_templ">
                                    <a href="{{ page.page_user_custom.get_absolute_url }}">
                                        {% if page.image %}
                                            <div class="page_img" style="background-image: url('{{page.image.url}}') ; "></div>
{#                                        <img src="{{page.image.url}}" alt="">#}

                                        {% else %}
                                         <div class="page_img_empty"></div>
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="disc_templ cab">
                                    <h3><a href="{{ page.page_user_custom.get_absolute_url }}">{{ page.page_user_custom.get_title }}</a></h3>
                                    <h2><span>{{ page.category }}</span></h2>
                                    <h4>{{page.page_user_custom.get_meta_description}}</h4>
                                    <h5><a href="#">Watch - {{ page.count_sum }}</a></h5>
                                </div>
                            </div>
                            {% empty %}
                            <h1> You have not created any templates yet. <a href="/start/">Let's
                                start!</a></h1>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>

            {% endblock %}

        </div>
    </div>

</div>


{% endblock %}

{% block scripts %}

<script>
    ClientApp.cabinet.filter_by_status();
</script>

{% endblock %}

{#{% render_block "js" %}#}

django_cms_example/templates/user_app/index.html
{% load navigation_tags %}
{% load cms_tags menu_tags sekizai_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}admin.min.css">
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    {% render_block "css" %}
</head>
<body>

<div id="page-wrapper">
    {% include 'user_app/includes/header.html' %}
    <!--<a href="{% if page.get_path %}/admin-cms/{{page.get_path}}{% endif %}">{{ page }} создана - {{ page.created_by }} id = {{ page.id }}</a>-->

    <div class="container" id="content_wrapper">
        {% block body %}

        {% endblock %}
    </div>
</div>

{% include 'user_app/includes/footer.html' %}
<div class="js-popup client-popup hidden">
    <div class=" fs-style  popup-content" data-action="register">
        <span class="js-close close">X</span>
        <h1 class="title-form">Sign up</h1>
        <div class="form-user">
            {% include 'user_app/partials/register_form.html' %}
        </div>
        <p class="js-switch switch-form-btn" data-action="login">
            <span>Вже маєте обліковий запис? </span>
            <span>Увійти!</span>
        </p>
    </div>


    <div class="fs-style popup-content hidden" data-action="login">
        <span class="js-close close">X</span>
        <h1 class="title-form">Sign in</h1>
        <div class="form-user">
            {% include 'user_app/partials/login_form.html' %}
        </div>
        <p class="js-switch switch-form-btn" data-action="register">
            <span>Немає облікового запису?</span>
            <span>Зареєструватись!</span>
        </p>
    </div>
</div>

<script src="{{ STATIC_URL }}admin.bundle.js"></script>

<script>
    ClientApp.auth_user.init();
    ClientApp.home.init();
</script>

{% block scripts %} {% endblock %}
{% render_block "js" %}

</body>
</html>

django_cms_example/templates/user_app/login.html
{% extends 'user_app/index.html' %}
{% block content %}
<form method="post" id="login_form" action="{% url 'login' %}"> {% csrf_token %}
    <div class="field-form">
        <label for="login">логін</label>
        <input type="text" name="login" id="login">
    </div>
    <div class="field-form">
        <label for="password">пароль</label>
        <input class="password" type="password" name="password" id="password">
    </div>
     <div class="checkbox-group">
        <input class="js-show-pass" id="show_pass_log" type="checkbox" name="show_password">
        <label for="show_pass_log">Показати пароль</label>
    </div>
    <span class="js-failed error hidden"></span>

     <div class="btn-popup-wrap">
        <button class="btn btn-popup w-50">Увійти</button>
    </div>
</form>
{% endblock %}

django_cms_example/templates/user_app/signup.html
{% extends 'user_app/index.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

django_cms_example/templates/user_app/start.html
{% extends 'user_app/index.html' %}



{% block content %}
<h1>ну шо , начинаем?</h1>

{% include 'user_app/partials/tree_category.html' %}
{% endblock %}
{#{% render_block "js" %}#}